return {

 simple = {
    { '1' , 'value', 5 },
    { '2' , 'value', 4 },
    { '3' , 'value', 7 },
    { '4' , 'value', 3 },
    { '6' , 'value', 10},
    { '7' , 'value', 13},
    { '8' , 'value', 9 }
  },

  texts = {

  },

  tweets = {
    { 't0', 'tweet', 'Natalia Arsand', 'nataliarsand Natalia Arsand\nMuito massa o produto de hoje no @eucompraria: http://migre.me/Bu3D' },
    { 't1', 'tweet', 'Claudio Busatto', 'elalemon Claudio Busatto\nA placa dos acréscimos sobe para avisar o Clementino que ele já tá liberado pra fazer o gol. #ClementinoFacts' },
    { 't2', 'tweet', 'Natalia Arsand', 'nataliarsand Natalia Arsand\nDescoberta valiosa do dia: musicuo.com. (thanks @rafb3!)' },
    { 't3', 'tweet', 'Arthur', '_F5 Arthur\nby mateusKahler\nAdoro quando meu santo baixa o diabo me acha e eu tenho um daqueles momentos de insight criativo que mais ninguém, além dimin, poderia ter.' },
    { 't4', 'tweet', 'Arin Hanson', 'egoraptor Arin Hanson\nGoing to the Tron Pop-up Shop today. YEAH BOYEE http://bit.ly/elkUpx' },
    { 't5', 'tweet', 'PRguitarman', 'PRguitarman PRguitarman\n"HOW DID HE BEAT ME IN THIS ONLINE MATCH??--oh, he\'s ASIAN!"' },
    { 't6', 'tweet', 'Linux Mall', 'LinuxMall Linux Mall\nO @Mundotecno fará #SORTEIO de Canecas Infectious Liquid. SIGA, RETWEET e concorra http://kingo.to/mN3 (sorteio 10/12)' },
    { 't7', 'tweet', 'Gabriel Oliveira', 'g_PA_Oliveira Gabriel Oliveira\nDa séria: coisas que nunca saberíamos se não fosse o twitter: @_INFO Mulher registra o Sol como sua propriedade. http://abr.io/AZJ' },
    { 't8', 'tweet', 'Mateus Kahler', 'mateusKahler Mateus Kahler\nNão importa a idade que eu tenha, acho que correr com o carrinho de super-mercado e pular em cima farei pra sempre.' },
    { 't9', 'tweet', 'Matheus Fialho', 'm_fialho Matheus Fialho\nTô protelando com essa monografia até chegar AMANHÃ que é o último dia pra fazer, só funciono a base da pressão #fato' },
    { 't10', 'tweet', 'Taiane Garcia', 'taaianegarcia Taiane Garcia\nvo lá montar a árvore de natal com o vitoor *.*' },
    { 't11', 'tweet', 'Matheus Fialho', 'm_fialho Matheus Fialho\nAI QUE LEGAL, HOJE VOU AO BANHEIRO MIJAR NO MICTÓRIO E OLHO PRO AZULEJO E TA ESCRITO "FIALHINHO LINDO" ADORO , aiai que merda. EUHUHEUIHUE' },
    { 't12', 'tweet', 'INI', 'acaixadomacaco INI\nA lista pro show do #INI (@acaixadomacaco) já passou dos 200 nomes. Corre que ainda dá tempo de mandar: ininoasteroid@gmail.com' },
    { 't13', 'tweet', 'Arin Hanson', 'egoraptor Arin Hanson\nIf you were to take a picture of me right now, I guarantee it\'d be blurry. #toofuckincold' },
    { 't14', 'tweet', 'Arin Hanson', 'egoraptor Arin Hanson\nIt\'s the coldest it\'s ever been in the apartment today, and the shower decides to not deliver hot water.' },
    { 't15', 'tweet', 'Linux Mall', 'LinuxMall Linux Mall\nPromoção @icultgeneration >> Porque devo ganhar produtos @LinuxMall? As melhores respostas ganham! http://kingo.to/n29' },
    { 't16', 'tweet', 'Matheus Fialho', 'm_fialho Matheus Fialho\nQuero que semana que vem chegue logo. _|_' },
    { 't17', 'tweet', 'Linux Mall', 'LinuxMall Linux Mall\nO @profissionaisti está sorteando canecas Infectious Liquid. SIGA, RETWEET e concorra http://kingo.to/mVX Sorteio 10/12.' },
    { 't18', 'tweet', 'Música para Baixar', 'MPBMusicaLivre Música para Baixar\nby samadeu\nDebate sobre Direitos Autorais c/ @samadeu @MarcelLeonardi @oteatromagico @ABRAMUS amanhã, às 20h http://zapt.in/Yjr #reformaLDA' },
    { 't19', 'tweet', 'Commandlinefu 10 up', 'commandlinefu10 Commandlinefu 10 up\nhttp://www.commandlinefu.com/commands/view/7144/generate-md5-hash-for-a-string - Generate MD5 hash for a string (unefunge) #bash #md5sum' },
    { 't20', 'tweet', 'Noelle Roccha', 'noellecr Noelle Roccha\nby mateusKahler\nhomens librianos: não curto.' },
    { 't21', 'tweet', 'Mateus Kahler', 'mateusKahler Mateus Kahler\nMais ou menos assim: As coisas se influenciam, então você consegue a relação completa entre elas, mas e o conjunto em relação a quê?' },
    { 't22', 'tweet', 'Mateus Kahler', 'mateusKahler Mateus Kahler\nUma escolha filosófica é determinante no tipo de pessoa que você é: Se você acredita em constantes arbitrárias.' },
    { 't23', 'tweet', 'Foforks', 'foforks Foforks\nby taaianegarcia\nQuote do dia: "- Não tenha medo - murmurei. - Nós pertencemos um ao outro."' },
    { 't24', 'tweet', 'William Shakespeare', 'famousphrases William Shakespeare\nby sshossain\n\'Seu futuro depende de muitas coisas, mas principalmente de você.\' Frank Tyger' },
    { 't25', 'tweet', 'Soraya S. Hossain', 'sshossain Soraya S. Hossain\n@\n@lfzawacki Aí está: http://goo.gl/svbCy :) Te recomendo fortemente o álbum "The Human Equation", o melhor deles na minha opinião!' },
    { 't26', 'tweet', 'Lucas Fialho Zawacki', 'lfzawacki Lucas Fialho Zawacki\n@\n@mateusKahler Haja barramentos hein? e as GPUs que se cuidem' },
    { 't27', 'tweet', 'Matheus Fialho', 'm_fialho Matheus Fialho\nAloneeee' },
    { 't28', 'tweet', 'Lucas Fialho Zawacki', 'lfzawacki Lucas Fialho Zawacki\nTava ouvindo o Operation Mindcrime II do Queensryche no carro hoje e PQP que som foda, recomendo galerinha' },
    { 't29', 'tweet', 'Lucas Fialho Zawacki', 'lfzawacki Lucas Fialho Zawacki\n@\n@sshossain Curti a música que tu mandou ontém, tem o link do torrent onde tu "comprou" essa discografia :) ?' },
    { 't30', 'tweet', 'fotanus', 'fotanus fotanus\n@jeronimofagunds: Doe: http://yfrog.com/moh7x0j' },
    { 't31', 'tweet', 'Carlos Villela', 'cv Carlos Villela\n…and by pr0n I mean "large binary artifacts", of course. Ahem.' },
    { 't32', 'tweet', 'Carlos Villela', 'cv Carlos Villela\nGit remotes can have multiple URLs configured, and push will distribute accordingly. Hmm. Why isn\'t this being used to distribute pr0n yet?' },
    { 't33', 'tweet', 'Linux Mall', 'LinuxMall Linux Mall\nO @ProfissionaisTI fará #SORTEIO de Canecas Infectious Liquid. SIGA, RETWEET e concorra http://kingo.to/mVX (sorteio 10/12)' },
    { 't34', 'tweet', 'Sarah Silverman', 'SarahKSilverman Sarah Silverman\nby PRguitarman\nElderly woman in line to board plane turned around and blew a long silent powerful burp onto my face' },
    { 't35', 'tweet', 'Natalia Arsand', 'nataliarsand Natalia Arsand\n"thanks!" "no, thank you!" "oh, please, thank YOU!" "ok... thanks"' },
    { 't36', 'tweet', 'fotanus', 'fotanus fotanus\nQue saudade que eu tava das letrinhas do C, mesmo ruby sendo tão bom' },
    { 't37', 'tweet', 'Linux Mall', 'LinuxMall Linux Mall\nFaça um curso de Java com 20% OFF na @Globalcode e ainda leve para casa um kit @LinuxMall http://bit.ly/ijsrFO' },
    { 't38', 'tweet', 'PRguitarman', 'PRguitarman PRguitarman\nFIESTA DENCHURA http://bit.ly/hNZGpF' },
    { 't39', 'tweet', 'Matheus Fialho', 'm_fialho Matheus Fialho\nEu e o @daniel_avesr aqui em casa estudando química loucamente uhu' },
    { 't40', 'tweet', 'Henrique Bastos', 'henriquebastos Henrique Bastos\nby AkitaOnRails\n*Consenso* só te dá a "segurança" de que se vc estiver errado, todo mundo se ferrou junto! #cya' },
    { 't41', 'tweet', 'Tecnoblog', 'tecnoblog Tecnoblog\nby sshossain\nApple contrata exército de advogados contra Android - http://bit.ly/ihuyiQ' },
    { 't42', 'tweet', 'Natalia Arsand', 'nataliarsand Natalia Arsand\nMargaux Lange utilizes salvaged Barbie doll parts on its art jewelry. http://grem.io/2jG' },
    { 't43', 'tweet', 'Soraya S. Hossain', 'sshossain Soraya S. Hossain\nPosso ser bem menininha às vezes, mas certas "frescuras" e "ataques" realmente me irritam.' },
    { 't44', 'tweet', 'PRguitarman', 'PRguitarman PRguitarman\nWoke up from a dream where TSA was taking blood samples. Lady said she\'d take it from my arm but then stabbed my neck. #WTFsubconscious' },
    { 't45', 'tweet', 'Jason Mustian', 'jasonmustian Jason Mustian\nby PRguitarman\n"I miss the days when people wouldn\'t steal music, and we could charge $14.99 for a CD we paid a Chinese boy 1¢ to make"--music industry' },
    { 't46', 'tweet', 'Rafael Bandeira', 'rafb3 Rafael Bandeira\nRT @desconf: Sabe quem vai na #desconf? O @fczuardi -- http://ow.ly/3hB2i | E você já se inscreveu? As vagas estão acabando!' },
    { 't47', 'tweet', 'Natalia Arsand', 'nataliarsand Natalia Arsand\nOk, now I am in the game for a healthier life! healthmonth.com/profile/natali… (cc @healthmonth)' },
    { 't48', 'tweet', 'zedshaw', 'zedshaw zedshaw\nSLAYER CHRISTMAS LIGHTS DISPLAY! http://www.youtube.com/watch?v=HFjI7gT1FvI&feature=fvw' },
    { 't49', 'tweet', 'Samuel Salamon', 'ssalamon Samuel Salamon\nBow your head and fold your hands master celebrator. No one gets a second chance master master.' },
    { 't50', 'tweet', 'Rafael Bandeira', 'rafb3 Rafael Bandeira\nWow, @healthmonth sponsorship system is genius! Like, every fitness/gym/health company will want to sponsor the world! @enjoymentland #win' },
    { 't51', 'tweet', 'Natalia Arsand', 'nataliarsand Natalia Arsand\nMassa >> http://keepachildalive.org/' },
    { 't52', 'tweet', 'PRguitarman', 'PRguitarman PRguitarman\n#whythe90srocked THIS IS THE RHYTHM OF THE NIGHT!' },
    { 't53', 'tweet', 'PRguitarman', 'PRguitarman PRguitarman\n#lolcomics on @thedailywhat ! http://j.mp/euTnW9' },
    { 't54', 'tweet', 'zedshaw', 'zedshaw zedshaw\nThe people in my building keep spamming me with their beefs with my landlord. Is there mailing list sites for renters/landlords?' },
    { 't55', 'tweet', 'Samuel Salamon', 'ssalamon Samuel Salamon\nmy closest friend Linoleum. Linoleum, supports my head, gives me something to believe *_*' },
    { 't56', 'tweet', 'Carlos Villela', 'cv Carlos Villela\nseelp depivraotin gvies me dyslixae' },
    { 't57', 'tweet', 'Linux Mall', 'LinuxMall Linux Mall\nJá está nevando na Linux Mall... Os pinguins do logotipo estão adorando a neve do Natal http://toma.ai/Jo' },
    { 't58', 'tweet', 'Kao Félix', 'kcfelix Kao Félix\nHow can eBay take up to 10 days to unsubscribe me from their annoying daily offers mailing list?' },
    { 't59', 'tweet', 'Linux Mall', 'LinuxMall Linux Mall\nCamiseta Hadouken http://bit.ly/fPxl5S' },
    { 't60', 'tweet', 'Linux Mall', 'LinuxMall Linux Mall\nCamiseta HP-MP http://bit.ly/hMpf4v' }
  },

  points = {
    { 'p1' , 'point', 1, 0 },
    { 'p2' , 'point', 1, 1 },
    { 'p3' , 'point', 2, 0 },
    { 'p4' , 'point', 3, 0 },
    { 'p5' , 'point', 3, 2 },
    { 'p6' , 'point', 0, 0 },
    { 'p7' , 'point', 5, 0 },
    { 'p8' , 'point', 6, 0 },
    { 'p9' , 'point', 7, 2 },
    {'p10' , 'point', 1, 0 },
    {'p11' , 'point', 1, 3 }
  },

  games = {
        { 'Donkey Kong Country Returns', 'value', 87.54 },
        { 'Disney Epic Mickey ', 'value', 77.85 },
        { 'Super Mario Galaxy 2 ', 'value', 97.07 },
        { 'Call of Duty: Black Ops ', 'value', 84.22 },
        { 'GoldenEye 007 ', 'value', 83.98 },
        { 'Sonic Colors ', 'value', 77.62 },
        { 'New Super Mario Bros. Wii ', 'value', 88.12 },
        { 'Monster Hunter Tri ', 'value', 85.0 },
        { 'Kirby\'s Epic Yarn ', 'value', 89.77 },
        { 'Super Smash Bros. Brawl ', 'value', 92.75 },
        { 'Michael Jackson The Experience ', 'value', 65.8 },
        { 'Pro Evolution Soccer 2011 ', 'value', 76.33 },
        { 'Snowpack Park', 'value', 60.0 },
        { 'Raving Rabbids: Travel in Time', 'value', 61.67 },
        { 'Sonic Colors', 'value', 77.62 },
        { 'Tom Clancy\'s Ghost Recon', 'value', 44.71 },
        { 'Need for Speed: Hot Pursuit', 'value', 40.0 },
        { 'Harry Potter and the Deathly Hallows, Part 1', 'value', 50.0 }

  },

}

